# Site settings
email: mmilloway87@gmail.com
baseurl: ""
paginate: 10
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Mel Milloway
description: Melissa Milloway is an instructional designer at Amazon in Seattle, WA. She specializes in designing and developing learning experiences and blogging about it.
url: "http://melslearninglab.com"
twitter_username: melmilloway
default_img: https://source.unsplash.com/qHblAFPy2uU/2000x1200

# Build settings
exclude: ["Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
